#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_HOMEDIR}app-root/runtime/

GEOS_LIBRARY_PATH=${OPENSHIFT_RUNTIME_DIR}lib/libgeos_c.so
GDAL_LIBRARY_PATH=${OPENSHIFT_RUNTIME_DIR}lib/libgdal.so
[ -f $GEOS_LIBRARY_PATH ] && [ -f $GEOS_LIBRARY_PATH ] || ${OPENSHIFT_REPO_DIR}.openshift/scripts/dbsetup
