#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

cartridge_type="python-2.6"
source $OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/bin/activate

echo "Installing project requirements"
pip install -r $OPENSHIFT_REPO_DIR/requirements.txt

echo "Injecting database settings into local_settings.py"
cat >> $OPENSHIFT_REPO_DIR/src/project/local_settings.py <<EOF
import os

DEBUG = (os.environ.get('DEBUG', False) == 'True')
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ['OPENSHIFT_APP_NAME'],
        'USER': os.environ['OPENSHIFT_POSTGRESQL_DB_USERNAME'],
        'PASSWORD': os.environ['OPENSHIFT_POSTGRESQL_DB_PASSWORD'],
        'HOST': os.environ['OPENSHIFT_POSTGRESQL_DB_HOST'],
        'PORT': os.environ['OPENSHIFT_POSTGRESQL_DB_PORT'],
    }
}

STATIC_ROOT = os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'static')

OPENSHIFT_RUNTIME_DIR = os.path.join(os.environ['$OPENSHIFT_HOMEDIR'], 'app-root', 'runtime')
GEOS_LIBRARY_PATH = os.path.join(OPENSHIFT_RUNTIME_DIR, 'lib/libgeos_c.so')
GDAL_LIBRARY_PATH = os.path.join(OPENSHIFT_RUNTIME_DIR, 'lib/libgdal.so')

EOF

echo "Syncing the database models"
$OPENSHIFT_REPO_DIR/src/manage.py syncdb --noinput

echo "Collecting static files"
$OPENSHIFT_REPO_DIR/src/manage.py collectstatic --noinput
