#!/bin/sh

#
# Install GeoDjango requirements.
# -------------------------------
#
OPENSHIFT_RUNTIME_DIR=${OPENSHIFT_HOMEDIR}app-root/runtime

cd $OPENSHIFT_TMP_DIR
wget http://download.osgeo.org/proj/proj-4.8.0.tar.gz
tar xzf proj-4.8.0.tar.gz
cd proj-4.8.0
./configure --prefix=$OPENSHIFT_RUNTIME_DIR
make
make install
cd ..
rm -rf ./proj-4.8.0*


cd $OPENSHIFT_TMP_DIR
wget http://download.osgeo.org/geos/geos-3.3.5.tar.bz2
tar xjf geos-3.3.5.tar.bz2
cd geos-3.3.5
./configure --prefix=$OPENSHIFT_RUNTIME_DIR
make
make install
cd ..
rm -rf ./geos-3.3.5*


cd $OPENSHIFT_TMP_DIR
wget ftp://ftp.remotesensing.org/gdal/gdal-1.9.1.tar.gz
tar zxf gdal-1.9.1.tar.gz
cd gdal-1.9.1
./configure --prefix=$OPENSHIFT_RUNTIME_DIR --disable-static --with-geos=$OPENSHIFT_RUNTIME_DIR/bin/geos-config
make
make install
cd ..
rm -rf ./gdal-1.9.1*

#
# Spatially enable your database.
# -------------------------------
#
# Here we assume that you're using your default database with the name of 
# your application.
OPENSHIFT_DB_NAME=$OPENSHIFT_APP_NAME

psql $OPENSHIFT_DB_NAME -c "create language plpgsql;"
psql -d $OPENSHIFT_DB_NAME -f /usr/share/pgsql/contrib/postgis-64.sql
psql -d $OPENSHIFT_DB_NAME -f /usr/share/pgsql/contrib/spatial_ref_sys.sql
